### ISSUE TITLE
SNS데이터 수집

### ISSUE THREAD

**Issue by dltmdfud** [2021-SMHRD-KDT-AI-1/SmartTrend#11]
- [x] 트위터 API를 이용해  키워드 데이터 수집 
- [x] 네이버 블로그 API를 이용해  키워드 데이터 수집 
- [x] 크롤링을 통한 인스타 키워드 데이터 수집
- [x] 크롤링을 통한 페이스북 키워드 데이터 수집
- [x] 네이버 API를 이용해 네이버 카페에서 키워드 데이터 수집
- [x] 네이버 API를 이용해 밴드 에서 키워드 데이터 수집 ( 현재까지 조사해본 결과 검색어로 조회기능 없음)
- [x] 카카오 API를 이용해 다음에서 키워드 데이터 수집
- [x] 인스타 API를 이용해 키워드 데이터  수집 
- [x] 페이스북 API를 이용해  키워드 데이터 수집 식당 숙박 여행지

**Comment by Koth100** [comment]
인스타그램 API에서 원하는 기능을 제공하지 않는것으로 보임.
