### ISSUE TITLE
학습 데이터 전처리

### ISSUE THREAD

**Issue by dltmdfud** [2021-SMHRD-KDT-AI-1/SmartTrend#13]
- [x] 한글 전처리 모델 확인/습득
- [x] 광고 전처리 모델 확인/습득
- [x] 전처리 작업

**Comment by princehd** [comment]
- JDK 1.8을 제외한 나머지 버전 삭제
- 새로운 가상환경 구축후 JPype, konlpy 설치
- JAVA_HOME 환경변수 path에 등록
