### ISSUE TITLE
지역 페이지

### ISSUE THREAD

**Issue by dltmdfud** [2021-SMHRD-KDT-AI-1/SmartTrend#9]
- [x] 지역페이지 표출
- [x] 사용자는 카테고리(관광,음식점,숙박등)중 하나를 선택한다.
- [x] 옆 공간에 머신러닝 하여 추천된 정보 노출

**Comment by Koth100** [comment]
네비게이션 메뉴에 맞게 요소를 분리하여 보여주고싶음 -> 각 요소별로 클래스를 부여후, 헤당 네비게이션 버튼 클릭시 해당하는 클래스를 보이게 그외 요소는 안보이게 조절
